# Generated by Django 2.0.2 on 2019-02-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('variantFirstCnt', models.IntegerField()),
                ('variantSecondCnt', models.IntegerField()),
                ('header', models.CharField(max_length=1024)),
                ('variantFirstDescr', models.CharField(max_length=1000)),
                ('variantSecondDescr', models.CharField(max_length=1000)),
            ],
        ),
    ]
