# Generated by Django 2.0.2 on 2019-02-02 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Variant')),
            ],
        ),
        migrations.RemoveField(
            model_name='voting',
            name='variantFirstCnt',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='variantFirstDescr',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='variantSecondCnt',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='variantSecondDescr',
        ),
        migrations.AddField(
            model_name='variant',
            name='votind_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Voting'),
        ),
    ]
