# Generated by Django 2.1.5 on 2019-02-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20190202_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='votind_id',
            new_name='voting_id',
        ),
    ]
